server {
    listen 80;
    server_name localhost;

    location /7caveiras/ {
        alias /usr/share/nginx/html/7caveiras/;
        index index.html index.htm;
        try_files $uri $uri/ /7caveiras/index.html;
    }

    # Raiz interna do container apenas entrega o index
    location / {
        root /usr/share/nginx/html/7caveiras;
        try_files $uri $uri/ /index.html;
    }
}
