services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tdu_backend
    ports:
      - "3000:3000"
    # volumes: - ./backend:/usr/src/app (REMOVER PARA DEPLOY)
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Passa a URL da API durante o build
        - VITE_API_URL=localhost:3000
    container_name: tdu_frontend
    ports:
      - "5173:80" # Mapeia a porta 80 interna para 5173 externa
    restart: always