services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: tdu_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - tdu_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # IMPORTANTE: Se for rodar local, use seu IP (ex: http://192.168.1.9:3000)
        # Se for no Render, use a URL que o Render te deu.
        - VITE_API_URL=http://localhost:3000
    container_name: tdu_frontend
    ports:
      - "5173:80" # Nginx roda na 80 interna, expomos na 5173
    restart: always
    depends_on:
      - backend
    networks:
      - tdu_network

networks:
  tdu_network:
    driver: bridge