name: TDU 7 Caveiras - Auto Deploy

on:
  push:
    branches:
      - main  # O deploy acontece sempre que você der push na main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Notificar Render (Backend)
        run: curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}

      - name: Notificar Render (Frontend)
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}